[project]
name = "etap21-feast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "feast==0.40.1",
    "pandas==2.2.3",
    "jupyter==1.1.1",
    "lab==8.2"
]
